--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp::Plugin::OnClick
  ApplicationName: TestApp-Plugin-OnClick
  ApplicationUUID: 45E1B0FE-820A-11DC-9905-76B28F38D863
  ConfigFileVersion: 2
  Database: 
    CheckSchema: 1
    Database: testapp_plugin_onclick
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - LetMe: {}

    - SkeletonApp: {}

    - REST: {}

    - Halo: {}

    - ErrorTemplates: {}

    - OnlineDocs: {}

    - CompressedCSSandJS: {}

    - AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Plugin::OnClick::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
