--- 
framework: 
  AdminMode: 1
  ApplicationClass: TestApp
  ApplicationName: TestApp
  ApplicationUUID: F3F2F2C8-E9BB-11DE-AFD7-6AEE7828A805
  ConfigFileVersion: 5
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: testapp_notifications
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: IO
  MailerArgs:
    - %log/mail.log%
  Plugins: 
    - AdminUI: {}
    - CompressedCSSandJS: {}
    - ErrorTemplates: {}
    - Halo: {}
    - LetMe: {}
    - OnlineDocs: {}
    - REST: {}
    - SkeletonApp: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: TestApp::Notifications::View
  View: 
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
