build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.640
license: Perl
name: Jifty
no_index: 
  directory: 
    - share
    - t
    - doc
    - inc
    - t
  package: 
    - DB
    - inc
recommends: 
  Class::Accessor::Named: 0
  DBD::SQLite: 0
  Devel::Cover: 0
  Module::CoreList: 0
  Module::Install::Admin: 0.50
  Module::Refresh: 0.09
  PAR::Dist::FromCPAN: 0
  Test::Base: 0.44
  Test::HTML::Lint: 0
  Test::HTTP::Server::Simple: 0.02
  Test::More: 0.62
  Test::Pod::Coverage: 0
  Test::WWW::Mechanize: 1.04
  WWW::Mechanize: 1.12
requires: 
  App::CLI: 0.03
  CGI: 3.19
  CGI::Cookie::Splitter: 0
  CSS::Squish: 0.05
  Cache::Cache: 0
  Calendar::Simple: 0
  Class::Accessor: 0
  Class::Container: 0
  Class::Data::Inheritable: 0
  Compress::Zlib: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  Data::Page: 0
  Date::Manip: 0
  DateTime: 0
  Email::Folder: 0
  Email::LocalDelivery: 0
  Email::MIME: 0
  Email::MIME::ContentType: 0
  Email::MIME::Creator: 0
  Email::Send: 1.99_01
  Email::Simple: 0
  Email::Simple::Creator: 0
  Exporter::Lite: 0
  File::Find::Rule: 0
  File::MMagic: 0
  File::ShareDir: 0.04
  HTML::Entities: 0
  HTML::Lint: 0
  HTML::Mason: 1.3101
  HTML::Mason::Plugin: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  HTTP::Server::Simple: 0.20
  HTTP::Server::Simple::Recorder: 0
  Hash::Merge: 0
  Hook::LexWrap: 0
  IPC::PubSub: 0.11
  JSON::Syck: 0.14
  Jifty::DBI: 0.29
  LWP::UserAgent: 0
  Locale::Maketext::Extract: 0.20
  Locale::Maketext::Lexicon: 0.60
  Log::Log4perl: 0
  MIME::Types: 0
  Module::CoreList: 0
  Module::Pluggable: 2.95
  Module::ScanDeps: 0
  Object::Declare: 0.13
  Params::Validate: 0
  Pod::Simple: 0
  SQL::ReservedWords: 0
  Scalar::Defer: 0.06
  Shell::Command: 0
  String::Koremutake: 0
  UNIVERSAL::require: 0
  URI: 0
  XML::Simple: 0
  XML::Writer: 0.601
  XML::XPath: 0
  YAML::Syck: 0.71
  perl: 5.8.3
  version: 0
tests: t/*.t t/*/t/*.t
version: 0.61123_01
