build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.630
license: Perl
name: Jifty
no_index: 
  directory: 
    - doc
    - inc
    - t
  package: 
    - DB
    - inc
requires: 
  App::CLI: 0.03
  CSS::Squish: 0.05
  Cache::Cache: 0
  Calendar::Simple: 0
  Class::Accessor: 0
  Class::Accessor::Named: 0
  Class::Container: 0
  Class::Data::Inheritable: 0
  Compress::Zlib: 0
  DBD::SQLite: 1.11
  Data::Page: 0
  Date::Manip: 0
  DateTime: 0
  Email::Folder: 0
  Email::LocalDelivery: 0
  Email::Send: 1.99_01
  Email::Simple: 0
  Email::Simple::Creator: 0
  File::Find::Rule: 0
  File::MMagic: 0
  File::ShareDir: 0
  HTML::Entities: 0
  HTML::Mason: 1.3101
  HTML::Mason::Plugin: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  HTTP::Server::Simple: 0.20
  HTTP::Server::Simple::Recorder: 0
  Hash::Merge: 0
  Hook::LexWrap: 0
  JSON::Syck: 0.13
  Jifty::DBI: 0.21
  LWP::UserAgent: 0
  Locale::Maketext::Extract: 0.20
  Locale::Maketext::Lexicon: 0.60
  Log::Log4perl: 0
  MIME::Types: 0
  Module::CoreList: 0
  Module::Install::Admin: 0.50
  Module::Pluggable: 2.95
  Module::Refresh: 0.09
  Params::Validate: 0
  Pod::Simple: 0
  String::Koremutake: 0
  Test::Base: 0.44
  Test::HTML::Lint: 0
  Test::HTTP::Server::Simple: 0.02
  Test::More: 0.62
  Test::Pod::Coverage: 0
  Test::WWW::Mechanize: 1.04
  UNIVERSAL::require: 0
  URI: 0
  WWW::Mechanize: 1.12
  XML::Simple: 0
  XML::Writer: 0
  XML::XPath: 0
  YAML::Syck: 0.45
  perl: 5.8.3
  version: 0
tests: t/*.t t/*/t/*.t
version: 0.60706
