--- 
framework: 
  SkipAccessControl: 1
  AdminMode: 1
  ApplicationClass: ShrinkURL
  ApplicationName: ShrinkURL
  ApplicationUUID: CA394F5C-7E9E-11DC-8297-EA4406D64C5E
  ConfigFileVersion: 2
  Database: 
    CheckSchema: 1
    Database: shrinkurl
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: DEBUG
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - 
      LetMe: {}

    - 
      SkeletonApp: {}

    - 
      REST: {}

    - 
      Halo: {}

    - 
      ErrorTemplates: {}

    - 
      OnlineDocs: {}

    - 
      CompressedCSSandJS: {}

    - 
      AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: ShrinkURL::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
