--- 
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Yada
no_index: 
  directory: 
    - inc
    - t
requires: 
  Jifty: 0.70117
version: 0.01
