--- 
framework: 
  SkipAccessControl: 1
  AdminMode: 1
  ApplicationClass: Doxory
  ApplicationName: Doxory
  ApplicationUUID: 181049AC-E029-11DB-A5EB-227D19064FA1
  Database: 
    CheckSchema: 1
    Database: doxory
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - SkeletonApp: {}
    - REST: {}
    - Halo: {}
    - ErrorTemplates: {}
    - CompressedCSSandJS: {}
    - Authentication::Password: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  TemplateClass: Doxory::View
  SkipAccessControl: 1
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
