--- 
framework: 
  AdminMode: 1
  ApplicationClass: Ping
  ApplicationName: Ping
  PubSub:
    Enable: 1
  Database: 
    CheckSchema: 1
    Database: ping
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.1
  DevelMode: 0
  L10N: 
    PoDir: share/po
  LogLevel: WARN
  Mailer: Sendmail
  MailerArgs: []

  Plugins: []

  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
    ServerClass: Jifty::Server::Fork
